#!/usr/bin/env python3
"""
Generate the GrabBox Android icons.

Produces, under android/app/src/main/res/:

    mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher{,_round}.png
        the pre-API-26 launcher icon, and the fallback on API 26+ for launchers
        that ignore the adaptive icon. A rounded brand tile with the mark on it.

    mipmap-anydpi-v26/ic_launcher{,_round}.xml
        the adaptive icon: a brand-gradient background with the mark on top.

    drawable/ic_launcher_bg.xml      background layer (gradient)
    drawable/ic_launcher_fg.xml      foreground layer (the mark)
    drawable/ic_launcher_mono.xml    themed-icon layer (single colour)
    drawable/ic_stat_grabbox.xml     notification icon, for the status bar

The last one is not cosmetic. DownloadService uses setSmallIcon() for the
foreground notification, and the status bar draws those as a flat silhouette -
pointing it at the colourful launcher icon is what produces the white blob.

Run:  python3 tools/make_android_icons.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import brand  # noqa: E402

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "android", "app", "src", "main", "res")

#: launcher icon sizes per density bucket
DENSITIES = (
    ("mdpi", 48), ("hdpi", 72), ("xhdpi", 96),
    ("xxhdpi", 144), ("xxxhdpi", 192),
)

#: the adaptive icon is 108x108, and launchers mask the middle 72x72 to a
#: circle or a squircle. 66 keeps the sparks clear of every mask we know of.
ADAPTIVE_VIEWPORT = 108
ADAPTIVE_SPAN = 66
#: the status bar draws a 24dp icon
STATUS_VIEWPORT = 24
STATUS_SPAN = 22


def _write(rel, text):
    path = os.path.normpath(os.path.join(RES, rel))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("  wrote %s" % os.path.relpath(path, RES))


def _launcher_pngs():
    for bucket, size in DENSITIES:
        folder = os.path.join(RES, "mipmap-%s" % bucket)
        os.makedirs(folder, exist_ok=True)
        # Full-bleed square: on API 26+ the launcher masks this itself, and a
        # pre-26 launcher that uses it wants the full square anyway.
        square = brand.render_tile(size, corner=False)
        n = brand.write_png(os.path.join(folder, "ic_launcher.png"),
                           square.buf, size)
        round_ = brand.render_tile(size, corner=False, round_mask=True)
        m = brand.write_png(os.path.join(folder, "ic_launcher_round.png"),
                           round_.buf, size)
        print("  wrote mipmap-%s/ic_launcher{,_round}.png (%d/%d B)"
              % (bucket, n, m))


def _adaptive_xmls():
    body = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<adaptive-icon xmlns:android=\"http://schemas.android.com/apk/res/android\">\n"
        '    <background android:drawable="@drawable/ic_launcher_bg" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_fg" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_mono" />\n'
        "</adaptive-icon>\n")
    _write("mipmap-anydpi-v26/ic_launcher.xml", body)
    _write("mipmap-anydpi-v26/ic_launcher_round.xml", body)


def _background():
    _write("drawable/ic_launcher_bg.xml", """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_android_icons.py - do not edit by hand. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="135"
        android:startColor="#%02X%02X%02X"
        android:endColor="#%02X%02X%02X"
        android:type="linear" />
</shape>
""" % (brand.TILE_TOP + brand.TILE_BOTTOM))


def _foreground():
    layers = brand.adaptive_foreground(ADAPTIVE_VIEWPORT, ADAPTIVE_SPAN)
    _write("drawable/ic_launcher_fg.xml",
           brand.vector_drawable(layers, ADAPTIVE_VIEWPORT,
                                 ADAPTIVE_VIEWPORT, ADAPTIVE_VIEWPORT))


def _monochrome():
    path = brand.silhouette_even_odd(ADAPTIVE_VIEWPORT, ADAPTIVE_SPAN)
    _write("drawable/ic_launcher_mono.xml", """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_android_icons.py - do not edit by hand.
     Cube with the arrow knocked out, so a themed launcher icon still shows
     the download arrow. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="%ddp"
    android:height="%ddp"
    android:viewportWidth="%g"
    android:viewportHeight="%g">
    <path
        android:pathData="%s"
        android:fillColor="#000000"
        android:fillType="evenOdd" />
</vector>
""" % (ADAPTIVE_VIEWPORT, ADAPTIVE_VIEWPORT, ADAPTIVE_VIEWPORT,
       ADAPTIVE_VIEWPORT, path))


def _status():
    path = brand.silhouette_even_odd(STATUS_VIEWPORT, STATUS_SPAN)
    _write("drawable/ic_stat_grabbox.xml", """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_android_icons.py - do not edit by hand.
     The notification icon. Solid white, no fillAlpha: the status bar
     tints small icons and discards the colour anyway. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="%ddp"
    android:height="%ddp"
    android:viewportWidth="%g"
    android:viewportHeight="%g">
    <path
        android:pathData="%s"
        android:fillColor="#FFFFFFFF"
        android:fillType="evenOdd" />
</vector>
""" % (STATUS_VIEWPORT, STATUS_VIEWPORT, STATUS_VIEWPORT, STATUS_VIEWPORT, path))


def main():
    print("rendering GrabBox Android icons ->", os.path.abspath(RES))
    _launcher_pngs()
    _adaptive_xmls()
    _background()
    _foreground()
    _monochrome()
    _status()
    print("done")


if __name__ == "__main__":
    main()
